Responsive-Web-Design Milestone 2
Coolczycki/Responsive-Web-Design pull request #4
Opened 2021-04-07 14:29 UTC by danmainah

2021-04-08 12:33 UTC, Elbie-em requested changes
## STATUS: CHANGES REQUIRED 🟡 

Hello @danmainah and @Loosescrew022, you have really worked hard on the project 💪 . You made a great effort meeting almost all the requirements for this milestone. However there some major issues that need to be fixed before this project can be approved.
See my comments within your code, in addition, other improvements indicated below.

## [TO IMPROVE]

- [x] Use of semantic HTML: misuse of sections in your code and makes it very hard for your code to read. Use this [link](https://www.w3schools.com/html/html5_semantic_elements.asp) as a guide on how to make your HTML semantic. 
      - Sections i.e Latest, Categories are the few designated for the *section* tag
      - Articles present in these sections should have an *article* tag
 Other areas could use non-semantic elements, your code compiles fine, but to make sure your page stands out and looks professional, kindly implement semantic practices.

- [x] The desktop version has a huge gap highlights and the Latest News section, please fix this so that it corresponds to the original
![Screenshot 2021-04-08 at 13 29 52](https://user-images.githubusercontent.com/57832450/114024355-3c495800-9874-11eb-963f-c46b0078f9b1.png)

- [ ] The Latest News section font sizing and element spacing should match the original
- [x] The Lastest News section images do not correspond to the original in your mobile version 
**Yours**
![Screenshot 2021-04-08 at 13 37 30](https://user-images.githubusercontent.com/57832450/114024666-9e09c200-9874-11eb-900f-79bb7f1b21cb.png)
**Original**
![Screenshot 2021-04-08 at 13 40 31](https://user-images.githubusercontent.com/57832450/114024705-aa8e1a80-9874-11eb-95f4-c3830ed79afd.png)

- [ ] The categories section contains duplicate articles, please fix this to match the original.
**Yours**
![Screenshot 2021-04-08 at 13 30 08](https://user-images.githubusercontent.com/57832450/114025081-08226700-9875-11eb-9073-a92a62ed3949.png)
**Original**
![Screenshot 2021-04-08 at 14 17 31](https://user-images.githubusercontent.com/57832450/114025227-31db8e00-9875-11eb-9881-f935cf3341e8.png)

- [ ] The categories section should have two categories per row in the tablet version.
**Yours**
![Screenshot 2021-04-08 at 13 46 00](https://user-images.githubusercontent.com/57832450/114025528-7ff09180-9875-11eb-9a22-597d10b192c0.png)
**Original**
![Screenshot 2021-04-08 at 14 21 10](https://user-images.githubusercontent.com/57832450/114025691-b201f380-9875-11eb-85a7-aa62ced7a1cc.png)

- [ ] The latest deals section font-sizing and spacing should match the original
- [ ] The latest deals section has duplicate titles, please fix this
- [ ] The latest deals section images don't match the original
![Screenshot 2021-04-08 at 13 51 22](https://user-images.githubusercontent.com/57832450/114025932-f8efe900-9875-11eb-803c-cafd69122d60.png).

- [ ] There is overflow in mobile and tablet versions, please fix this.

### *Kindly make changes and submit another code review,*
### *All the best, I cant wait to see the final product 😄 *

*As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 code reviews left for this project.*

*Feel free to contact me for any questions*

> Elbie Moonga (Part-time TSE)

> Github (@Elbie-em)
> Slack (Elbie Moonga)
> Twitter ([@ElbieEm](https://twitter.com/ElbieEm))
> LinkedIn([Elbie Moonga](https://www.linkedin.com/in/elbiemoonga/))

2021-04-08 12:33 UTC, Elbie-em commented on index.css
>    main {
This breakpoint should be 1024px

2021-04-08 12:33 UTC, Elbie-em commented on index.html
> +
Articles in this section should use the article tag, the latest section should be a wrapper generally, same for other sections.

2021-04-08 12:33 UTC, Elbie-em commented on index.html
> +		<section class="news-cont">
Fix duplication in this section as mentioned in main comments.

2021-04-08 19:53 UTC, Dipeshtwis requested changes
# Status:  ♻️ Changes Required ♻️
 Hi @danmainah and @Loosescrew022

**You've fixed almost all the requirements from the previous review. Well done.** Here're the major highlights of this PR:
- Your PR title and description are really descriptive.
- Good use of Semantic HTML.

**However, in order to approve, we have to work a little bit more. Please check my comments below and fix them as appropriate.**


## For Approval

- [ ] Still, there is overflow in mobile and tablet versions, please fix this. I have attached the screenshot below.
- The one marked with blue is overlapping with the previous content ( from 320px to 452px).
- The one marked with violet is overflowing if the size goes below 410px. I recommend here using some margin and padding.
- The one marked with blue is starting from the right side due to an overlap issue in almost every screen size. Please fix that.

![Screenshot (1310)_LI](https://user-images.githubusercontent.com/22434660/114086551-5d3f9680-98d0-11eb-9ed7-be6dab3d7d50.jpg)

## [Optional]

- [x] As this is not mentioned previously. I'm making this optional to fix this. In less than 480px screen size it is only showing two lists instead of 3. ( `Latest funding section`).

![Screenshot (1311)_LI](https://user-images.githubusercontent.com/22434660/114087316-5f562500-98d1-11eb-9a76-1acaa5da6d7b.jpg)

- [ ] Use the DRY (Do not repeat yourself) principle wherever possible. I have mentioned some of them in the comments.
- [ ] It would be nice if you create the discount triangle over the top right corner of the image of each article in the `Latest Deals section`.


Remember, This is optional and nothing to do with the project approval.

## Please make the required changes and submit another review request when you are done.

## Reminder

**"As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) now, you have only 1 code review left for this project. If you think that the code review was not fair, you can [request a second-opinion using this form](https://airtable.com/shrQAqnBwek5a0O0s). "**


(Feel free to contact me on slack by the handle of  **deep** if you have any additional questions).
Happy Coding
[Dipesh Kumar](https://deeptwist.tk)
[Twitter](https://twitter.com/97deepeshkumar)

2021-04-08 19:53 UTC, Dipeshtwis commented on index.css
> +  justify-content: flex-end;
[Optional]
You have repeated almost all the properties in `.news-cont-imgx` classes where x = 2,3,4,5,6,7,8,9. you can use DRY principle like this.

```
.news-cont-img,
.news-cont-img2,
.news-cont-img3
.news-cont-img4,
......,
 {
  height: 35%;
  width: 100%;
  background-position: center;
  background-size: cover;
  display: flex;
  flex-direction: column;
  justify-content: flex-end;
  padding: 12px;
}
```

2021-04-09 08:00 UTC, DeliceLydia approved these changes
# Status: Approved ![image](https://user-images.githubusercontent.com/44745855/114148289-e202d280-9919-11eb-8168-52607a255317.png) ![image](https://user-images.githubusercontent.com/44745855/114148322-e9c27700-9919-11eb-9cac-2f5c1d095b18.png)

Congratulations @danmainah and @Loosescrew022 for implementing all requested changes this shows your hardworking spirit and readiness to improve 

- Your project is looking good on both mobile, tablet, and desktop devices
- README is descriptive
- PR is descriptive

next time try to group classes with the same properties to apply DRY rules

## Kudos once again feel free to merge and move on to the next project

All the best,

Lydia Ingabire

2021-04-09 08:11 UTC, merged